import type { WorkflowConfig } from "./WorkflowCore";

/** Diagram A — Trade-to-payout lifecycle (user / LP perspective) */
export const TRADE_TO_PAYOUT_CONFIG: WorkflowConfig = {
  title: "Trade-to-Payout Lifecycle",
  subtitle: "user-lifecycle.workflow",
  // Neon green accent
  accentColor: "#39FF14", // Neon green
  labelScale: 1.05,
  width: 1120,
  height: 260,
  nodes: [
    {
      id: "bet",
      label: "User Places Bet\nStake locked",
      x: 90,
      y: 120,
      w: 150,
      h: 64,
      shape: "rounded",
      // Neon blue
      color: "#00FFFF",
      fill: "#00FFFF",
      // glow: true, // if supported by renderer
      processing: true,
    },
    {
      id: "close",
      label: "Cell Closes\n(5s Window)",
      x: 300,
      y: 120,
      w: 140,
      h: 60,
      shape: "rounded",
      // Neon yellow
      color: "#FFFF00",
      fill: "#FFFF00",
      // glow: true,
      // style: {
        // filter: 'drop-shadow(0 0 12px #FFFF00)'
        // }
    },
    {
      id: "tick",
      label: "Win/Loss Decision\n(Mathematical Models)",
      x: 530,
      y: 120,
      w: 160,
      h: 60,
      shape: "rounded",
      // Coral color for Win / Loss
      color: "#FF7F50", // Coral
      fill: "#FF7F50", // Coral
      processing: true,
      // glow: true,
      // style: {
      //   filter: 'drop-shadow(0 0 16px #FF7F50)'
      // }
      // style: {
      //   filter: 'drop-shadow(0 0 16px #FF7F50)'
      // }
    },
    {
      id: "zk",
      label: "30-sec ZK Proof\n→ Solana",
      x: 770,
      y: 120,
      w: 170,
      h: 64,
      shape: "rounded",
      // Neon orange replacing purple
      color: "#FFA500",
      fill: "#FFA500",
      // glow: true,
      // style: {
      //   filter: 'drop-shadow(0 0 16px #FFA500)'
      // }
    },
    {
      id: "claim",
      label: "Merkle Claim\nTrustless payout",
      x: 1010,
      y: 120,
      w: 170,
      h: 64,
      shape: "rounded",
      // Neon green
      color: "#39FF14",
      fill: "#39FF14",
      processing: true,
      // glow: true,
      // style: {
      //   filter: 'drop-shadow(0 0 20px #39FF14)'
      // }
    },
  ],
  edges: [
    {
      id: "e1",
      from: "bet",
      to: "close",
      label: "grid signed",
      labelPos: { x: 210, y: 75 },
      // color: "#66FCF1", // Lighter neon blue edge
                  // style: {
                  //   filter: 'drop-shadow(0 0 6px #00FFFF)'
                  // }
    },
    {
      id: "e2",
      from: "close",
      to: "tick",
      label: "realtime settlement",
      labelPos: { x: 410, y: 75 },
      // color: "#FFFF00", // Neon yellow edge
        // style: {
        //   filter: 'drop-shadow(0 0 6px #FFFF00)'
        // }
    },
    {
      id: "e3",
      from: "tick",
      to: "zk",
      label: "batch commits",
      labelPos: { x: 650, y: 75 },
      // color: "#FFA500", // Neon orange edge replacing purple
      // style: {
      //   filter: 'drop-shadow(0 0 6px #FFA500)'
      // }
    },
    {
      id: "e4",
      from: "zk",
      to: "claim",
      label: "sent to solana",
      labelPos: { x: 890, y: 75 },
      // color: "#39FF14", // Neon green edge
      // style: {
      //   filter: 'drop-shadow(0 0 8px #39FF14)'
      // }
    },
  ],
  steps: [
    { edgeId: "e1", desc: "User picks a cell; stake is locked against the signed grid." },
    { edgeId: "e2", desc: "The 5-second trading window closes; settlement clock starts." },
    { edgeId: "e3", desc: "Binance aggTrade drives the candle close — win/loss is immediate." },
    { edgeId: "e4", desc: "Every minute the keeper aggregates a batch and posts a Groth16 proof; winners claim with a Merkle proof." },
  ],
};

/** Diagram B — Centralized vs Carnot (provable fairness) */
export const PROVABLE_FAIRNESS_CONFIG: WorkflowConfig = {
  title: "Provable Fairness vs Centralized",
  subtitle: "fairness-compare.workflow",
  accentColor: "#F87171",
  labelScale: 1,
  width: 1040,
  height: 440,
  groupBoxes:[
    {
      label: "Traditional prediction market",
      x: 48,
      y: 18,
      w: 560,
      h: 170,
      color: "#ff4f4f",
    },
    {
      label: "Carnot prediction market",
      x: 48,
      y: 210,
      w: 870,
      h: 220,
      color: "#4ed3ea",
    },
  ],
  nodes: [
    {
      id: "t_bet",
      label: "Trader",
      x: 140,
      y: 100,
      w: 100,
      h: 52,
      shape: "rounded",
      color: "#63ffed",
    },
    {
      id: "t_box",
      label: "Operator\nBlack Box",
      x: 320,
      y: 100,
      w: 150,
      h: 68,
      shape: "rounded",
      color: "#945fff",
      fill: "#b253ff",
    },
    {
      id: "t_out",
      label: "Opaque\nsettlement",
      x: 520,
      y: 100,
      w: 130,
      h: 56,
      shape: "rounded",
      color: "#ff4949",
    },
    {
      id: "c_bet",
      label: "Trader",
      x: 140,
      y: 320,
      w: 100,
      h: 52,
      shape: "rounded",
      color: "#60edfa",
    },
    {
      id: "c_bn",
      label: "Binance\naggTrade",
      x: 330,
      y: 260,
      w: 130,
      h: 56,
      shape: "rounded",
      color: "#22D3EE",
    },
    {
      id: "c_py",
      label: "Pyth\non-chain",
      x: 330,
      y: 380,
      w: 130,
      h: 56,
      shape: "rounded",
      color: "#818CF8",
    },
    {
      id: "c_zk",
      label: "ZK Proof Lock\nSP1 circuit",
      x: 570,
      y: 320,
      w: 170,
      h: 64,
      shape: "rounded",
      color: "#FB923C",
      fill: "#FB923C",
      processing: true,
    },
    {
      id: "c_sol",
      label: "Solana\nverify + vault",
      x: 810,
      y: 320,
      w: 150,
      h: 60,
      shape: "rounded",
      color: "#34D399",
      fill: "#34D399",
    },
  ],
  edges: [
    {
      id: "e1",
      from: "t_bet",
      to: "t_box",
      label: "trust",
      labelPos: { x: 220, y: 90 },
    },
    {
      id: "e2",
      from: "t_box",
      to: "t_out",
      label: "???",
      labelPos: { x: 415, y: 90 },
    },
    {
      id: "e3",
      from: "c_bet",
      to: "c_bn",
      label: "OHLC",
      labelPos: { x: 220, y: 280 },
    },
    {
      id: "e4",
      from: "c_bet",
      to: "c_py",
      label: "anchor",
      labelPos: { x: 215, y: 375 },
    },
    {
      id: "e5",
      from: "c_bn",
      to: "c_zk",
      label: "cross-check",
      labelPos: { x: 450, y: 270 },
    },
    {
      id: "e6",
      from: "c_py",
      to: "c_zk",
      label: "≤ 2% bound",
      labelPos: { x: 450, y: 375 },
    },
    {
      id: "e7",
      from: "c_zk",
      to: "c_sol",
      label: "Groth16",
      labelPos: { x: 700, y: 305 },
    },
  ],
  steps: [
    { edgeId: "e1", desc: "User must trust the operator's hidden matching engine." },
    { edgeId: "e2", desc: "Settlement is a black box — no cryptographic proof of correctness." },
    { edgeId: "e3", desc: "Carnot builds OHLC from the same Binance stream users experience." },
    { edgeId: "e4", desc: "Public Pyth checkpoints anchor trustless oracle prices on-chain." },
    { edgeId: "e5", desc: "The circuit binds OHLC to Binance ticks inside the batch window." },
    { edgeId: "e6", desc: "Three Pyth samples enforce |OHLC − Pyth| ≤ 200 bps — backend cannot lie." },
    { edgeId: "e7", desc: "Only a valid proof unlocks the Solana program state and vault payout." },
  ],
};

/** Diagram D — ZK settlement pipeline (batch state machine) */
export const ZK_SETTLEMENT_PIPELINE_CONFIG: WorkflowConfig = {
  title: "ZK Settlement Pipeline",
  subtitle: "batch-state-machine.workflow",
  accentColor: "#A78BFA",
  labelScale: 1.05,
  width: 1080,
  height: 340,
  nodes: [
    {
      id: "db",
      label: "PostgreSQL\nOrders",
      x: 130,
      y: 240,
      w: 140,
      h: 58,
      shape: "rounded",
      color: "#8bbbfa",
    },
    {
      id: "ch",
      label: "ClickHouse\nOHLC",
      x: 130,
      y: 120,
      w: 140,
      h: 56,
      shape: "rounded",
      color: "#FBBF24",
    },
    {
      id: "pend",
      label: "PENDING\nBatch assembly",
      x: 380,
      y: 180,
      w: 190,
      h: 68,
      shape: "rounded",
      color: "#60A5FA",
      fill: "#60A5FA",
      processing: true,
    },
    {
      id: "prove",
      label: "ZK_PROVING\nSP1 · carnot-circuit",
      x: 650,
      y: 180,
      w: 220,
      h: 68,
      shape: "rounded",
      color: "#FB923C",
      fill: "#FB923C",
      processing: true,
    },
    {
      id: "chain",
      label: "ON_CHAIN\nverify_and_settle",
      x: 930,
      y: 180,
      w: 200,
      h: 64,
      shape: "rounded",
      color: "#34D399",
      fill: "#34D399",
    },
    {
      id: "fields",
      label: "20-field public\noutput preimage",
      x: 650,
      y: 300,
      w: 200,
      h: 52,
      shape: "rounded",
      color: "#94A3B8",
    },
  ],
  edges: [
    {
      id: "e1",
      from: "db",
      to: "pend",
      label: "SETTLED rows",
      labelPos: { x: 250, y: 235 },
    },
    {
      id: "e2",
      from: "ch",
      to: "pend",
      label: "candles",
      labelPos: { x: 250, y: 135 },
    },
    {
      id: "e3",
      from: "pend",
      to: "prove",
      label: "witness + constraints",
      labelPos: { x: 505, y: 135 },
    },
    {
      id: "e4",
      from: "prove",
      to: "chain",
      label: "Groth16 proof",
      labelPos: { x: 795, y: 135 },
    },
    {
      id: "e5",
      from: "prove",
      to: "fields",
      label: "hash",
      labelPos: { x: 675, y: 245 },
    },
  ],
  steps: [
    { edgeId: "e1", desc: "Worker gathers all settled orders and Merkle inputs from PostgreSQL." },
    { edgeId: "e2", desc: "ClickHouse supplies gapless 5-second OHLC covering the batch window." },
    { edgeId: "e3", desc: "Batch status PENDING — SP1 zkVM executes the Rust circuit over the witness." },
    { edgeId: "e4", desc: "Keeper submits verify_and_settle; BN254 pairing verifies on Solana." },
    { edgeId: "e5", desc: "Public outputs preimage (20 fields) binds the proof to vault, Merkle root, and pool math." },
  ],
};

/** Diagram E — Five-layer quantitative pricing stack */
export const FIVE_LAYER_PRICING_STACK_CONFIG: WorkflowConfig = {
  title: "Five-Layer Pricing Stack",
  subtitle: "quant-stack.workflow",
  accentColor: "#22D3EE",
  labelScale: 1,
  width: 990,
  height: 580,
  nodes: [
    {
      id: "l1",
      label: "Layer 1\nEGARCH(1,1)\nVolatility Engine",
      x: 460,
      y: 30,
      w: 220,
      h: 52,
      shape: "rounded",
      color: "#FB923C",
      fill: "#FB923C",
      processing: true,
    },
    {
      id: "l2",
      label: "Layer 2\nHawkes Jump-Diffusion\nSobol QMC",
      x: 460,
      y: 130,
      w: 220,
      h: 52,
      shape: "rounded",
      color: "#22D3EE",
      fill: "#22D3EE",
      processing: true,
    },
    {
      id: "l3",
      label: "Layer 3\nKou Barrier\nCorrection",
      x: 460,
      y: 232,
      w: 220,
      h: 52,
      shape: "rounded",
      color: "#818CF8",
      fill: "#818CF8",
      processing: true,
    },
    {
      id: "l4",
      label: "Layer 4\nAvellaneda-Stoikov\nVPIN Gate",
      x: 460,
      y: 332,
      w: 220,
      h: 52,
      shape: "rounded",
      color: "#F472B6",
      fill: "#F472B6",
      processing: true,
    },
    {
      id: "l5",
      label: "Layer 5\nEVT CVaR\nRisk Management",
      x: 460,
      y: 438,
      w: 220,
      h: 52,
      shape: "rounded",
      color: "#F87171",
      fill: "#F87171",
      processing: true,
    },
    {
      id: "out",
      label: "Signed Grid Cell\nreward rate + band",
      x: 460,
      y: 540,
      w: 220,
      h: 52,
      shape: "rounded",
      color: "#34D399",
      fill: "#34D399",
    },
  ],
  edges: [
    {
      id: "e1",
      from: "l1",
      to: "l2",
      label: "σ_t · λ_t",
      labelPos: { x: 410, y: 80 },
    },
    {
      id: "e2",
      from: "l2",
      to: "l3",
      label: "paths → barrier",
      labelPos: { x: 400, y: 184 },
    },
    {
      id: "e3",
      from: "l3",
      to: "l4",
      label: "P_touch",
      labelPos: { x: 410, y: 288 },
    },
    {
      id: "e4",
      from: "l4",
      to: "l5",
      label: "quoted mult",
      labelPos: { x: 410, y: 386 },
    },
    {
      id: "e5",
      from: "l5",
      to: "out",
      label: "pool-safe",
      labelPos: { x: 410, y: 494 },
    },
  ],
  steps: [
    { edgeId: "e1", desc: "EGARCH + Hawkes produce time-varying σ_t and jump intensity." },
    { edgeId: "e2", desc: "Jump-diffusion with Sobol QMC estimates fair probability per cell." },
    { edgeId: "e3", desc: "Kou correction refines near-barrier touch probability." },
    { edgeId: "e4", desc: "AS quoter + VPIN gate skew quotes against toxic flow." },
    { edgeId: "e5", desc: "EVT-calibrated CVaR enforces pool-level tail risk limits." },
  ],
};

/** Diagram F — Cryptographic oracle binding (Pyth + 2% rule) */
export const CRYPTO_ORACLE_BINDING_CONFIG: WorkflowConfig = {
  title: "Cryptographic Oracle Binding",
  subtitle: "pyth-zk-bridge.workflow",
  accentColor: "#818CF8",
  labelScale: 1,
  width: 1000,
  height: 360,
  groupBox: {
    label: "1-minute settlement batch window",
    x: 30,
    y: 18,
    w: 960,
    h: 320,
    color: "#818CF8",
  },
  nodes: [
    {
      id: "ohlc",
      label: "OHLC Stream\n5s candles",
      x: 120,
      y: 200,
      w: 150,
      h: 58,
      shape: "rounded",
      color: "#22D3EE",
      fill: "#22D3EE",
      processing: true,
    },
    {
      id: "cp1",
      label: "Pyth CP₁\nwindow_start",
      x: 350,
      y: 110,
      w: 130,
      h: 54,
      shape: "rounded",
      color: "#818CF8",
    },
    {
      id: "cp2",
      label: "Pyth CP₂\nmidpoint",
      x: 370,
      y: 200,
      w: 130,
      h: 54,
      shape: "rounded",
      color: "#818CF8",
    },
    {
      id: "cp3",
      label: "Pyth CP₃\nwindow_end",
      x: 350,
      y: 290,
      w: 130,
      h: 54,
      shape: "rounded",
      color: "#818CF8",
    },
    {
      id: "bps",
      label: "Circuit B6\n|Close − Pyth| ≤ 2%",
      x: 620,
      y: 200,
      w: 210,
      h: 64,
      shape: "rounded",
      color: "#FB923C",
      fill: "#FB923C",
      processing: true,
    },
    {
      id: "zk",
      label: "Cannot forge\nproof if violated",
      x: 890,
      y: 200,
      w: 170,
      h: 58,
      shape: "rounded",
      color: "#34D399",
    },
  ],
  edges: [
    {
      id: "e1",
      from: "ohlc",
      to: "cp1",
      label: "nearest close",
      labelPos: { x: 200, y: 145 },
    },
    {
      id: "e2",
      from: "ohlc",
      to: "cp2",
      label: "nearest close",
      labelPos: { x: 255, y: 185 },
    },
    {
      id: "e3",
      from: "ohlc",
      to: "cp3",
      label: "nearest close",
      labelPos: { x: 195, y: 255 },
    },
    {
      id: "e4",
      from: "cp1",
      to: "bps",
      label: "≤200 bps",
      labelPos: { x: 500, y: 142 },
    },
    {
      id: "e5",
      from: "cp2",
      to: "bps",
      label: "≤200 bps",
      labelPos: { x: 480, y: 188 },
    },
    {
      id: "e6",
      from: "cp3",
      to: "bps",
      label: "≤200 bps",
      labelPos: { x: 500, y: 260 },
    },
    {
      id: "e7",
      from: "bps",
      to: "zk",
      label: "constraint gate",
      labelPos: { x: 770, y: 160 },
    },
  ],
  steps: [
    { edgeId: "e1", desc: "Each checkpoint compares on-chain Pyth to the nearest OHLC close." },
    { edgeId: "e4", desc: "Constraint B6: deviation must stay within MAX_DEVIATION_BPS = 200." },
    { edgeId: "e7", desc: "If any comparison fails, SP1 aborts — no Groth16 proof, no settlement." },
    { edgeId: "e2", desc: "Mid-window checkpoint anchors drift halfway through the batch." },
    { edgeId: "e3", desc: "Final checkpoint binds the terminal price used for outcomes." },
    { edgeId: "e5", desc: "Three sorted oracle reads prevent cherry-picking alternate anchors." },
    { edgeId: "e6", desc: "End-state binding closes the cryptographic oracle bridge." },
  ],
};
